# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e512e22540f37f1604c90bca37920f685a56c87fd7a4e7a2ada6a749354ae0c81e8c896b3327a03969fc4356f8cb19245c883872243bb594fa438d7c785a046a

test:
  secret_key_base: dc529088f6131bb7b6dfdbb1914315919707703376b4a0e0a9705d00fd3a215c872db87641a8c8c05c33805c82266de735922abeadf9ccd68080225a1d3c93cc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
